BASE = 6242624000

ITEM_MAPPING = {
    [BASE + 0] = {"p_bow", "progressive"},
    [BASE + 1] = {"p_boomerang", "progressive"},
    [BASE + 2] = {"p_hookshot", "progressive"},
    [BASE + 3] = {"p_bombs", "progressive"},
    [BASE + 4] = {"p_firerod", "progressive"},
    [BASE + 5] = {"p_icerod", "progressive"},
    [BASE + 6] = {"p_hammer", "progressive"},
    [BASE + 7] = {"p_sandrod", "progressive"},
    [BASE + 8] = {"p_tornadorod", "progressive"},
    [BASE + 9] = {"bell", "toggle"},
    [BASE + 10] = {"staminascroll", "toggle"},
    [BASE + 11] = {"bowoflight", "toggle"},
    [BASE + 12] = {"pegasusboots", "toggle"},
    [BASE + 13] = {"flippers", "toggle"},
    [BASE + 14] = {"p_bracelet", "progressive"},
    [BASE + 15] = {"p_shield", "progressive", 2},
    [BASE + 16] = {"smooth_gem", "toggle"},
    -- [BASE + 17] = {"letter", "toggle"},
    [BASE + 18] = {"trade", "progressive", 2},
    [BASE + 19] = {"pouch", "toggle"},
    [BASE + 20] = {"bee_badge", "toggle"},
    [BASE + 21] = {"hint_glasses", "toggle"},
    -- [BASE + 22] = {"charm", "toggle"},
    [BASE + 23] = {"great_spin", "toggle"},
    [BASE + 24] = {"quake", "progressive"},
    -- [BASE + 25] = {"green_rupee", "consumable"}
    -- [BASE + 26] = {"blue_rupee", "consumable"}
    -- [BASE + 27] = {"red_rupee", "consumable"}
    -- [BASE + 28] = {"purple_rupee", "consumable"}
    -- [BASE + 29] = {"silver_rupee", "consumable"}
    -- [BASE + 30] = {"gold_rupee", "consumable"}
    [BASE + 31] = {"maiamai", "consumable"},
    -- [BASE + 32] = {"monster_guts", "consumable"}
    -- [BASE + 33] = {"monster_horn", "consumable"}
    -- [BASE + 34] = {"monster_tail", "consumable"}
    -- [BASE + 35] = {"piece_of_heart", "consumable"}
    -- [BASE + 36] = {"heart_container", "consumable"}
    [BASE + 37] = {"empty_bottle", "progressive"},
    [BASE + 38] = {"p_lamp", "progressive"},
    [BASE + 39] = {"p_sword", "progressive"},
    [BASE + 40] = {"p_glove", "progressive"},
    [BASE + 41] = {"p_net", "progressive"},
    [BASE + 42] = {"p_mail", "progressive"},
    [BASE + 43] = {"masterore", "progressive"},
    -- Dungeon Items
    [BASE + 44] = {"hs_small_key", "consumable"},
    [BASE + 45] = {"ls_small_key", "consumable"},
    [BASE + 46] = {"ep_compass", "toggle"},
    [BASE + 47] = {"ep_big_key", "toggle"},
    [BASE + 48] = {"ep_small_keys", "consumable"},
    [BASE + 49] = {"hg_compass", "toggle"},
    [BASE + 50] = {"hg_big_key", "toggle"},
    [BASE + 51] = {"hg_small_keys", "consumable"},
    [BASE + 52] = {"th_compass", "toggle"},
    [BASE + 53] = {"th_big_key", "toggle"},
    [BASE + 54] = {"th_small_keys", "consumable"},
    [BASE + 55] = {"pd_compass", "toggle"},
    [BASE + 56] = {"pd_big_key", "toggle"},
    [BASE + 57] = {"pd_small_keys", "consumable"},
    [BASE + 58] = {"sp_compass", "toggle"},
    [BASE + 59] = {"sp_big_key", "toggle"},
    [BASE + 60] = {"sp_small_keys", "consumable"},
    [BASE + 61] = {"sw_compass", "toggle"},
    [BASE + 62] = {"sw_big_key", "toggle"},
    [BASE + 63] = {"sw_small_keys", "consumable"},
    [BASE + 64] = {"tt_compass", "toggle"},
    [BASE + 65] = {"tt_big_key", "toggle"},
    [BASE + 66] = {"tt_small_key", "consumable"},
    [BASE + 67] = {"ir_compass", "toggle"},
    [BASE + 68] = {"ir_big_key", "toggle"},
    [BASE + 69] = {"ir_small_keys", "consumable"},
    [BASE + 70] = {"dp_compass", "toggle"},
    [BASE + 71] = {"dp_big_key", "toggle"},
    [BASE + 72] = {"dp_small_keys", "consumable"},
    [BASE + 73] = {"tr_compass", "toggle"},
    [BASE + 74] = {"tr_big_key", "toggle"},
    [BASE + 75] = {"tr_small_keys", "consumable"},
    [BASE + 76] = {"lc_compass", "toggle"},
    [BASE + 77] = {"lc_small_keys", "consumable"},
}
