name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - guigui0246
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report; please fill in with as much detail as possible.
        If you need PopTracker logs for your bug report, you can enable logging for PopTracker by going to %AppData%/PopTracker, opening `PopTracker.json` and changing `"log": false,` to `"log": true,"`. A `log.txt` will then be made in the same folder, next to `PopTracker.json`.
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-issue checklist
      description: Please make sure you have done all of the following steps first;
      options:
        - label: I have searched the existing issues to make sure this hasn't already been reported.
          required: true
        - label: I have made sure I am on the latest version of the tracker pack.
          required: true
        - label: I have asked on Discord, and made sure this is a tracker issue.
          required: true
  - type: checkboxes
    id: checklist-2
    attributes:
      label: More Infos
      description: Please select all that apply;
      options:
        - label: I am using the auto-track feature.
          required: false
        - label: I am running the multiworld on archipelago.gg.
          required: false
        - label: I am running the multiworld on my own server.
          required: false
        - label: I am using the latest stable release of Archipelago.
          required: false
        - label: I am using a beta release of Archipelago.
          required: false
        - label: I am using a beta release of the tracker pack.
          required: false
  - type: dropdown
    id: ap-version
    attributes:
      label: What version of APWorld are you using?
      description: Please select the version of APWorld you are using.
      options:
        - v0.1.x
        - v0.2.0
        - v0.2.1
        - v0.2.2
        - v0.2.3+
        - Not from https://github.com/randomsalience/albw-archipelago/
    validations:
      required: true
  - type: dropdown
    id: bug-type
    attributes:
      label: What kind of issue are you running into?
      description: Is it an issue with logic (e.g. what the tracker says is not accurate to what randomizer logic should be) or is it a display issue (e.g. the tracker says you already cleared a check or item that you didn't, yet)
      options:
        - Logic issue
        - Auto-track issue (portraits, events and non-randomized items cannot be tracked)
        - Display issue
        - Other...
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue?
      description: What happened? And what should have happened instead? If relevant, provide your obtained items, defeated bosses, etc. Also, feel free to upload relevant screenshots of your game, the tracker and Discord chats.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: options
    attributes:
      label: What are your options?
      description: The options you selected in the tracker pack and the options your multiworld is running with are very helpful to reproduce your issue. If you think they are relevant, please list them here or upload a screenshot of your tracker and multiworld options.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please drag and drop your relevant `log.txt` here.
    validations:
      required: false
