Tracker:AddItems("items/items.json")
Tracker:AddItems("items/items_mother_maiamai.json")
-- Tracker:AddItems("items/items_tfh.json")
Tracker:AddItems("items/items_chests.json")
Tracker:AddItems("items/items_keys.json")
-- Tracker:AddItems("items/items_maps.json")
Tracker:AddItems("items/items_display.json")
Tracker:AddItems("items/items_dungeons.json")
-- Tracker:AddItems("items/items_labels.json")
Tracker:AddItems("items/items_cracks.json")
--Tracker:AddItems("items/items_prizes.json")
Tracker:AddItems("items/items_settings.json")
Tracker:AddItems("items/items_weather_vanes.json")
