name: Pack Checker

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  validate-pack:
    name: Validate pack with pack-checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: PopTracker/pack-checker-action@v1
